{{ config(
    alias = 'vw_emploi_eff_secteur_prive_gds_secteurs'
    )
}}
WITH 
exploded AS (
    SELECT data->'results' AS result
    FROM {{ source('bronze', 'emploi_eff_secteur_prive_gds_secteurs') }}  
)
SELECT
    result->>'region' AS region,
    result->>'ancienne_region' AS ancienne_region,
    result->>'departement' AS departement,
    result->>'zone_d_emploi' AS zone_d_emploi,
    result->>'epci' AS epci,
    result->>'commune' AS commune,
    result->>'intitule_commune' AS intitule_commune,
    result->>'grand_secteur_d_activite' AS grand_secteur_d_activite,
    result->>'secteur_na17' AS secteur_na17,
    result->>'secteur_na38' AS secteur_na38,
    result->>'secteur_na88' AS secteur_na88,
    result->>'ape' AS ape,
    result->>'code_region' AS code_region,
    result->>'code_ancienne_region' AS code_ancienne_region,
    result->>'code_departement' AS code_departement,
    result->>'code_zone_d_emploi' AS code_zone_d_emploi,
    result->>'code_epci' AS code_epci,
    result->>'code_commune' AS code_commune,
    result->>'code_ape' AS code_ape,
    result->>'effectifs_salaries_2006' AS effectifs_salaries_2006,
    result->>'effectifs_salaries_2007' AS effectifs_salaries_2007,
    result->>'effectifs_salaries_2008' AS effectifs_salaries_2008,
    result->>'effectifs_salaries_2009' AS effectifs_salaries_2009,
    result->>'effectifs_salaries_2010' AS effectifs_salaries_2010,
    result->>'effectifs_salaries_2011' AS effectifs_salaries_2011,
    result->>'effectifs_salaries_2012' AS effectifs_salaries_2012,
    result->>'effectifs_salaries_2013' AS effectifs_salaries_2013,
    result->>'effectifs_salaries_2014' AS effectifs_salaries_2014,
    result->>'effectifs_salaries_2015' AS effectifs_salaries_2015,
    result->>'effectifs_salaries_2016' AS effectifs_salaries_2016,
    result->>'effectifs_salaries_2017' AS effectifs_salaries_2017,
    result->>'effectifs_salaries_2018' AS effectifs_salaries_2018,
    result->>'effectifs_salaries_2019' AS effectifs_salaries_2019,
    result->>'effectifs_salaries_2020' AS effectifs_salaries_2020,
    result->>'effectifs_salaries_2021' AS effectifs_salaries_2021,
    result->>'effectifs_salaries_2022' AS effectifs_salaries_2022,
    result->>'effectifs_salaries_2023' AS effectifs_salaries_2023,
    result->>'nombre_d_etablissements_2006' AS nombre_d_etablissements_2006,
    result->>'nombre_d_etablissements_2007' AS nombre_d_etablissements_2007,
    result->>'nombre_d_etablissements_2008' AS nombre_d_etablissements_2008,
    result->>'nombre_d_etablissements_2009' AS nombre_d_etablissements_2009,
    result->>'nombre_d_etablissements_2010' AS nombre_d_etablissements_2010,
    result->>'nombre_d_etablissements_2011' AS nombre_d_etablissements_2011,
    result->>'nombre_d_etablissements_2012' AS nombre_d_etablissements_2012,
    result->>'nombre_d_etablissements_2013' AS nombre_d_etablissements_2013,
    result->>'nombre_d_etablissements_2014' AS nombre_d_etablissements_2014,
    result->>'nombre_d_etablissements_2015' AS nombre_d_etablissements_2015,
    result->>'nombre_d_etablissements_2016' AS nombre_d_etablissements_2016,
    result->>'nombre_d_etablissements_2017' AS nombre_d_etablissements_2017,
    result->>'nombre_d_etablissements_2018' AS nombre_d_etablissements_2018,
    result->>'nombre_d_etablissements_2019' AS nombre_d_etablissements_2019,
    result->>'nombre_d_etablissements_2020' AS nombre_d_etablissements_2020,
    result->>'nombre_d_etablissements_2021' AS nombre_d_etablissements_2021,
    result->>'nombre_d_etablissements_2022' AS nombre_d_etablissements_2022,
    result->>'nombre_d_etablissements_2023' AS nombre_d_etablissements_2023
FROM exploded
