# Singa Green #1B4429
# Singa Yellow #F5D819
# Singa Grey #E8ECEA


[theme]
base="light"
backgroundColor="white"
secondaryBackgroundColor="#E8ECEA"
textColor="#1B4429"
baseRadius="full"
seondaryColor="#F5D819"


[theme.sidebar]
backgroundColor="#1B4429"
secondaryBackgroundColor="#E8ECEA"
textColor="#F5D819"
secondaryTextColor="#1B4429"