dbt_odis:
  target: dev_live
  outputs:
    dev_live:
      dbname: prefect
      host: localhost
      pass: prefect
      port: 5432
      schema: bronze
      threads: 16
      type: postgres
      user: prefect

    dev_custom:
      dbname: prefect
      host: localhost
      pass: prefect
      port: 5432
      schema: JBN
      threads: 16
      type: postgres
      user: prefect
