dbt_odis:
  target: dev_custom
  outputs:
    dev_live:
      dbname: odis
      host: localhost
      pass: odis
      port: 5432
      schema: bronze
      threads: 16
      type: postgres
      user: odis

    dev_custom:
      dbname: odis
      host: localhost
      pass: odis
      port: 5432
      schema: JBN
      threads: 16
      type: postgres
      user: odis
