name: 'Setup Python'
description: 'Setup Python with Poetry and install dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
    
    - name: Install dependencies
      shell: bash
      run: |
        poetry install --no-interaction