name: execute

on: push

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Extract logement
        uses: ./.github/actions/extract
        with:
          domain: logement.logements_total

      - name: Load logement
        uses: ./.github/actions/load
        with:
          domain: logement.logements_total