name: pre-commit & unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install poetry
      run: |
        python -m pip install poetry
        poetry self add poetry-plugin-export
        poetry export --with dev --format=requirements.txt --output=requirements.txt

    - name: set PY
      run: echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> "${GITHUB_ENV}"

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Install python dependencies
      run: poetry install --no-interaction

    - name: Validate datasources.yaml
      run: |
        yq eval '.' datasources.yaml > /dev/null
        echo "datasources.yaml is valid YAML"

    - name: Execute unit tests 
      run: poetry run pytest -v

    - name: Verify tests results
      if: ${{ failure() }}
      run: exit 1
