name: 'Record Pipeline Operation Status'
description: 'Record the status of an operation (extract/load) for a domain'

inputs:
  operation:
    description: 'Operation name (extract/load)'
    required: true
  domain:
    description: 'Domain name'
    required: true
  outcome:
    description: 'Operation outcome (success/failure)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Record operation status
      shell: bash
      run: |
        mkdir -p ./status
        if [ "${{ inputs.outcome }}" == "success" ]; then
          echo "success" > "./status/${{ inputs.domain }}_${{ inputs.operation }}_status.txt"
          echo "✅ ${{ inputs.operation }} for domain ${{ inputs.domain }} succeeded" >> "./status/${{ inputs.domain }}_${{ inputs.operation }}_message.txt"
        else
          echo "failure" > "./status/${{ inputs.domain }}_${{ inputs.operation }}_status.txt"
          echo "❌ ${{ inputs.operation }} for domain ${{ inputs.domain }} failed" >> "./status/${{ inputs.domain }}_${{ inputs.operation }}_message.txt"
        fi
    
    - name: Upload status
      uses: actions/upload-artifact@v4
      with:
        name: status-${{ inputs.operation }}-${{ inputs.domain }}
        path: ./status/
        retention-days: 1
